version: "3.8"

services:
  configserver:
    image: oz/configserver
    build:
      context: ../../
      dockerfile: Dockerfile
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - ecommerce
    environment:
      SPRING_APPLICATION_NAME: configserver
  eurekaserver:
    image: oz/eurekaserver
    build:
      context: ../../../eurekaserver
      dockerfile: Dockerfile
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - ecommerce
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_APPLICATION_NAME: eurekaserver
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  gatewayserver:
    image: oz/gatewayserver
    build:
      context: ../../../gatewayserver
      dockerfile: Dockerfile
    mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
      - ecommerce
    depends_on:
      - configserver
      - eurekaserver
      - usermanagement
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_APPLICATION_NAME: gatewayserver
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/


  usermanagement:
    image: oz/users
    build:
      context: ../../../usermanagement
      dockerfile: Dockerfile
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - ecommerce
    depends_on:
      - configserver
      - eurekaserver
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_APPLICATION_NAME: users
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/users
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ozkan
      SPRING_FLYWAY_SCHEMAS: ecommerce_users_schema
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: http://keycloak:8080/auth/realms/ecommerce-realm

    links:
      - postgres
      - keycloak




  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: ozkan
      DB_PORT: 5432
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
    networks:
      - ecommerce

  flywayUser:
    image: flyway/flyway:7.15.0
    volumes:
      - ./UserDBMigration:/flyway/sql
    command: migrate
    depends_on:
      - postgres
    environment:
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=ozkan
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/users
      - FLYWAY_SCHEMAS=ecommerce_users_schema
      - FLYWAY_GROUP=true

  postgres:
    container_name: postgres
    restart: always
    image: "postgres:13"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ozkan
      - POSTGRES_DB=products
      - POSTGRES_DB=users
      - POSTGRES_DB=keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ecommerce

  flywayProduct:
    image: flyway/flyway:7.15.0
    volumes:
      - ./ProductDBMigration:/flyway/sql
    command: migrate
    depends_on:
      - postgres
    environment:
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=ozkan
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/products
      - FLYWAY_SCHEMAS=ecommerce_products_schema
      - FLYWAY_GROUP=true

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: Ozge.Ozkan@adesso.com.tr
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - ecommerce


networks:
  ecommerce:

volumes:
  pgadmin_data:
  postgres_data:
  data: {}
  cache:
  keycloak_data:
