mongodb:
  image:  mongo:latest
  container_name: mongodb
  environment:
    - MONGO_INITDB_ROOT_USERNAME=rootuser
    - MONGO_INITDB_ROOT_PASSWORD=rootpass
  restart: unless-stopped
  ports:
    - "27017:27017"
  volumes:
    - data:/data
mongo-express:
  image: mongo-express
  container_name: mexpress
  environment:
    - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
    - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
    - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
    - ME_CONFIG_MONGODB_SERVER=mongodb

  links:
    - mongodb
  restart: unless-stopped
  ports:
    - "8088:8081"

redis:
  image: redis:6.2-alpine
  restart: always
  ports:
    - "6379:6379"
  volumes:
    - cache:/data


  ordermanagement:
    image: oz/oders
    build:
      context: ../../../ordermanagement
      dockerfile: Dockerfile
    mem_limit: 700m
    ports:
      - "9002:9002"
    networks:
      - ecommerce
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_APPLICATION_NAME: order
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
      MONGODB_URI: mongodb://mongodb:27017/order

    links:
      - mongodb

  productmanagement:
    image: oz/products
    build:
      context: ../../../productmanagement
      dockerfile: Dockerfile
    mem_limit: 700m
    ports:
      - "9001:9001"
    networks:
      - ecommerce
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_APPLICATION_NAME: products
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
    links:
      - postgres